### ISSUE TITLE
Javascript: React Testing Part I- the second example test fails to pass

### ISSUE THREAD

**Issue by myshkins** [TheOdinProject/curriculum#25173]
### Describe your suggestion

In the Javascript course in the React Testing Part I lesson, the second example test does not pass. 
_How to reproduce:_
1. Follow the lesson. Run `create-react-app`
2. Remove boilerplate in App.js and App.test.js.
3. Copy the code from the lesson. 
`App.js`
```
import React, { useState } from "react";

const App = () => {
  const [heading, setHeading] = useState("Magnificent Monkeys");

  const clickHandler = () => {
    setHeading("Radical Rhinos");
  };

  return (
    <>
      <button type="button" onClick={clickHandler}>
        Click Me
      </button>
      <h1>{heading}</h1>
    </>
  );
};

export default App;
```

`App.test.js`
```
import React from "react";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import App from "./App";

describe("App component", () => {
  it("renders magnificent monkeys", () => {
    // since screen does not have the container property, we'll destructure render to obtain container for this test
    const { container } = render(<App />);
    expect(container).toMatchSnapshot();
  });

  it("renders radical rhinos after button click", () => {
    render(<App />);
    const button = screen.getByRole("button", { name: "Click Me" });

    userEvent.click(button);

    expect(screen.getByRole("heading").textContent).toMatch(/radical rhinos/i);
  });
});
```
4. run `npm test`

[Here](https://github.com/myshkins/TOP-react-testing-bug) is a github repo which includes all of the above steps 

Here is the error message I receive.
```
console.error
    Warning: An update to App inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at App (/home/myshkins/TOP-react-testing-bug/src/App.js:4:41)

       5 |
       6 |   const clickHandler = () => {
    >  7 |     setHeading("Radical Rhinos");
         |     ^
       8 |   };
       9 |
      10 |   return (

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:27589:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:25508:5)
      at setHeading (node_modules/react-dom/cjs/react-dom.development.js:17527:7)
      at clickHandler (src/App.js:7:5)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:4164:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:4213:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4277:31)
      at invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:4291:25)
      at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:9041:3)
      at processDispatchQueueItemsInOrder (node_modules/react-dom/cjs/react-dom.development.js:9073:7)
      at processDispatchQueue (node_modules/react-dom/cjs/react-dom.development.js:9086:5)
      at dispatchEventsForPlugins (node_modules/react-dom/cjs/react-dom.development.js:9097:3)
      at node_modules/react-dom/cjs/react-dom.development.js:9288:12
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:26140:12)
      at batchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:3991:12)
      at dispatchEventForPluginEventSystem (node_modules/react-dom/cjs/react-dom.development.js:9287:3)
      at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (node_modules/react-dom/cjs/react-dom.development.js:6465:5)
      at dispatchEvent (node_modules/react-dom/cjs/react-dom.development.js:6457:5)
      at dispatchDiscreteEvent (node_modules/react-dom/cjs/react-dom.development.js:6430:5)
      at HTMLDivElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLButtonElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLButtonElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLButtonElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at node_modules/@testing-library/dom/dist/events.js:19:20
      at Object.eventWrapper (node_modules/@testing-library/dom/dist/config.js:25:23)
      at fireEvent (node_modules/@testing-library/dom/dist/events.js:12:35)
      at Function.fireEvent.<computed> [as click] (node_modules/@testing-library/dom/dist/events.js:110:36)
      at fireClick (node_modules/@testing-library/user-event/dist/click.js:150:20)
      at clickElement (node_modules/@testing-library/user-event/dist/click.js:91:5)
      at Object.click (node_modules/@testing-library/user-event/dist/click.js:140:5)
      at Object.<anonymous> (src/App.test.js:17:15)

 FAIL  src/App.test.js
  App component
    ✓ renders magnificent monkeys (16 ms)
    ✕ renders radical rhinos after button click (42 ms)

  ● App component › renders radical rhinos after button click

    expect(received).toMatch(expected)

    Expected pattern: /radical rhinos/i
    Received string:  "Magnificent Monkeys"

      17 |     userEvent.click(button);
      18 |
    > 19 |     expect(screen.getByRole("heading").textContent).toMatch(/radical rhinos/i);
         |                                                     ^
      20 |   });
      21 | });

      at Object.<anonymous> (src/App.test.js:19:53)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   1 passed, 1 total
Time:        0.267 s, estimated 1 s
Ran all test suites.

Watch Usage: Press w to show more.
```

_Comments_
I was able to resolve this issue by updating `testing-library/user-event` to verison 14.0.0 and updating `App.test.js` to be async.
`App.test.js`
```
import React from 'react';
import { render, screen } from '@testing-library/react';
import "@testing-library/jest-dom"
import userEvent from "@testing-library/user-event"
import App from "./App"

describe("App component", () => {
  it("renders magnificent monkeys", () => {
    const { container } = render(<App />)
    expect(container).toMatchSnapshot()
  })

  it("renders radical rhinos after button click", async () => {
    const user = userEvent.setup()
    render(<App />)
    const button = screen.getByRole("button")

    await user.click(button)

    expect(screen.getByRole("heading").textContent).toMatch(/radical rhinos/i)
  })
})
```

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-react-testing-part-1#simulating-user-events

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

lemonheart

**Comment by mystic-cat** [comment]
I didn't get the same error. But had a similar issue with the test failing. 
Since setHeading is async the test fails without a timeout or async call placed on the event as suggested above.
